### ISSUE TITLE
Not working in OS X 10.9.5

### ISSUE THREAD

**Issue by politicus** [frdmn/alfred-dongers#2]
Interesting workflow. Thanks for sharing!

I get the following error:

Starting debug for 'Productivity Dongers'

[INFO: alfred.workflow.input.scriptfilter] Warning: Invalid argument supplied for foreach() in /Users/User/../Alfred.alfredpreferences/workflows/user.workflow.6B6F7452-1154-40CB-BA17-D7C12C94618B/wrapper.php on line 60
<?xml version="1.0"?>
<items/>
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 4.)'. Row (null), Col (null): 'Document is empty' in XML:
Warning: Invalid argument supplied for foreach() in /Users/User/../Alfred.alfredpreferences/workflows/user.workflow.6B6F7452-1154-40CB-BA17-D7C12C94618B/wrapper.php on line 60
<?xml version="1.0"?>
<items/>

**Comment by frdmn** [comment]
Can you retry [version 0.3.0](https://github.com/frdmn/alfred-dongers/releases/tag/0.3.0)? I'm going to close this issue for now, feel free to reopen if you still run into this problem :)
